@startuml packages_class_ports
set namespaceSeparator none
package "ports" as ports {
}
package "ports.acudiente_repo" as ports.acudiente_repo {
}
package "ports.alerta_repo" as ports.alerta_repo {
}
package "ports.asignacion_repo" as ports.asignacion_repo {
}
package "ports.asistencia_repo" as ports.asistencia_repo {
}
package "ports.auditoria_repo" as ports.auditoria_repo {
}
package "ports.cierre_repo" as ports.cierre_repo {
}
package "ports.configuracion_repo" as ports.configuracion_repo {
}
package "ports.convivencia_repo" as ports.convivencia_repo {
}
package "ports.estadisticos_repo" as ports.estadisticos_repo {
}
package "ports.estudiante_repo" as ports.estudiante_repo {
}
package "ports.evaluacion_repo" as ports.evaluacion_repo {
}
package "ports.habilitacion_repo" as ports.habilitacion_repo {
}
package "ports.infraestructura_repo" as ports.infraestructura_repo {
}
package "ports.institucion_repo" as ports.institucion_repo {
}
package "ports.nivelacion_repo" as ports.nivelacion_repo {
}
package "ports.periodo_repo" as ports.periodo_repo {
}
package "ports.plan_mejoramiento_repo" as ports.plan_mejoramiento_repo {
}
package "ports.service_ports" as ports.service_ports {
}
package "ports.siee_repo" as ports.siee_repo {
}
package "ports.usuario_repo" as ports.usuario_repo {
}
ports --> ports.acudiente_repo
ports --> ports.alerta_repo
ports --> ports.asignacion_repo
ports --> ports.asistencia_repo
ports --> ports.auditoria_repo
ports --> ports.cierre_repo
ports --> ports.configuracion_repo
ports --> ports.convivencia_repo
ports --> ports.estadisticos_repo
ports --> ports.estudiante_repo
ports --> ports.evaluacion_repo
ports --> ports.habilitacion_repo
ports --> ports.infraestructura_repo
ports --> ports.periodo_repo
ports --> ports.service_ports
ports --> ports.usuario_repo
@enduml
