@startuml packages_class_auth
set namespaceSeparator none
package "auth" as auth {
}
package "auth.bcrypt_auth" as auth.bcrypt_auth {
}
package "auth.bcrypt_auth_service" as auth.bcrypt_auth_service {
}
package "auth.jwt_handler" as auth.jwt_handler {
}
auth --> auth.bcrypt_auth_service
auth --> auth.jwt_handler
@enduml
