@startuml packages_class_domain
set namespaceSeparator none
package "models" as models {
}
package "models.acudiente" as models.acudiente {
}
package "models.alerta" as models.alerta {
}
package "models.asignacion" as models.asignacion {
}
package "models.asistencia" as models.asistencia {
}
package "models.auditoria" as models.auditoria {
}
package "models.cierre" as models.cierre {
}
package "models.configuracion" as models.configuracion {
}
package "models.convivencia" as models.convivencia {
}
package "models.dtos" as models.dtos {
}
package "models.estudiante" as models.estudiante {
}
package "models.evaluacion" as models.evaluacion {
}
package "models.habilitacion" as models.habilitacion {
}
package "models.infraestructura" as models.infraestructura {
}
package "models.institucion" as models.institucion {
}
package "models.nivelacion" as models.nivelacion {
}
package "models.periodo" as models.periodo {
}
package "models.piar" as models.piar {
}
package "models.plan_mejoramiento" as models.plan_mejoramiento {
}
package "models.usuario" as models.usuario {
}
@enduml
