@startuml packages_class_context_init
set namespaceSeparator none
package "context" as context {
}
package "context.context_initializer" as context.context_initializer {
}
package "context.session_context" as context.session_context {
}
context --> context.context_initializer
@enduml
